spring.application.name=demo

 

spring.data.redis.host=localhost
spring.data.redis.port=6379

# langchain4j.ollama.chat-model.temperature=0.1
# langchain4j.ollama.chat-model.num-predict=200
#langchain4j.ollama.chat-model.model-name=llama3.2:1b
# Endereço do servidor Ollama rodando na sua máquina
#langchain4j.ollama.chat-model.base-url=http://localhost:11434

# Nome do modelo que voce baixou com "ollama pull"
#langchain4j.ollama.chat-model.model-name=llama3.2

# Opcional: ver no console o que esta sendo enviado/recebido do modelo
# langchain4j.ollama.chat-model.log-requests=true
# langchain4j.ollama.chat-model.log-responses=true

# langchain4j.ollama.embedding-model.model-name=nomic-embed-text
# langchain4j.ollama.embedding-model.timeout=180s
 
